In [1]:
import numpy as np
import torch

1. Create two random tensors with shapes (6, 5) and (1, 5), and perform a matrix multiplication on these tensors.

In [118]:
# Set the random seed so things are predictable
torch.random.manual_seed(42)

# Create random tensors
tensor1 = torch.randn(6, 5)
tensor2 = torch.randn(1, 5)

# Perform matrix multiplication
# result = tensor1 @ tensor2.t()
# result = torch.mm(tensor1, tensor2.t())
result = torch.matmul(tensor1, tensor2.t())

# Print the result
print(result)

tensor([[ 1.2771],
        [-3.1890],
        [-3.3020],
        [-1.6132],
        [-2.5010],
        [-1.4270]])


In [66]:
tensor1.reshape(3, 10)

tensor([[-1.3076,  0.9676,  0.2162,  0.9594,  0.1784, -0.1793, -0.5584, -0.8804,
         -0.9581, -0.7895],
        [ 1.5681,  1.5774, -0.4480,  1.8764,  0.9119, -1.6227,  0.6528,  0.4743,
         -1.1011, -0.5321],
        [-0.5346, -1.4052, -0.7136, -1.6181, -0.9208, -0.9451, -1.3551, -1.0257,
         -0.8582, -0.4748]])

In [87]:
torch.random.manual_seed(42)

tensor1 = torch.arange(40).view(4, 5, 2)

# print(tensor1)
tensor1.permute(2, 1, 0).shape

torch.Size([2, 4, 5])

2. Given the provided code for generating data, create a simple Python function or class that multiplies the generated features tensor by the corresponding weights tensor and adds the bias term. Assume that the function/class takes the features, weights, and bias tensors as inputs and returns the result of the linear operation. Provide an example of using this function/class with the generated data.

In [88]:
# Generate some data
torch.manual_seed(7)  # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 5))
# True weights for our data, random normal variables again
weights = torch.randn_like(features)
# and a true bias term
bias = torch.randn((1, 1))

def linear_operation(features, weights, bias):
    # Perform linear operation
    result = torch.matmul(features, weights.t()) + bias
    return result


# Perform linear operation using the function
output = linear_operation(features, weights, bias)

print(output)

tensor([[-1.6619]])


3. Find the maximum and minimum values as well as the corresponding index values in the output of task 1.

In [119]:
# Find max
print('max:', torch.max(result, dim=0))

# Find min
print('min:', torch.min(result))

# Find arg max

print('argmax:', torch.argmax(result))

# Find arg min
print('argmin:', torch.argmin(result))

max: torch.return_types.max(
values=tensor([1.2771]),
indices=tensor([0]))
min: tensor(-3.3020)
argmax: tensor(0)
argmin: tensor(2)


4. Generate a unique tensor with dimensions (1, 1, 1, 25), and subsequently transform it into a new tensor by removing all singleton dimensions, resulting in a tensor with shape (25).

In [103]:
# Generate the initial tensor with shape (1, 1, 1, 25)
initial_tensor = torch.randn(1, 1, 1, 25)

# Remove singleton dimensions to obtain a tensor with shape (25)
new_tensor = initial_tensor.squeeze()

# Print the shape of the new tensor
print(new_tensor.size())

torch.Size([25])


5. Create a 1D tensor of size 5 with value ranging from 1 to 5. Reshape the 1D tensor into a 2D tensor of shape (1, 5)

In [106]:
# Create the 1D tensor with values ranging from 1 to 5
tensor_1d = torch.arange(1, 6)

# Reshape the 1D tensor into a 2D tensor of shape (1, 5)
# tensor_2d = tensor_1d.reshape(1, 5)
# tensor_2d = tensor_1d.view(1, 5)
tensor_2d = tensor_1d.unsqueeze(0)

# Print the shape and values of the 2D tensor
print("Shape of the 2D tensor:", tensor_2d.shape)
print("Values of the 2D tensor:", tensor_2d)

Shape of the 2D tensor: torch.Size([1, 5])
Values of the 2D tensor: tensor([[1, 2, 3, 4, 5]])


In [113]:
tensor_1d[:, None] == tensor_1d.unsqueeze(1)

tensor([[True],
        [True],
        [True],
        [True],
        [True]])

In [108]:
tensor_1d[None, :].shape

torch.Size([1, 5])

6. Create two 2D tensors of shape (2, 3) and perform element-wise addition.

In [114]:
# Create the first 2D tensor
tensor1 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Create the second 2D tensor
tensor2 = torch.tensor([[7, 8, 9], [10, 11, 12]])

# Perform element-wise addition of the two tensors
result = tensor1 + tensor2

# Print the resulting tensor
print(result)

tensor([[ 8, 10, 12],
        [14, 16, 18]])


7. Create a 2D tensor of shape (4, 4) filled with random values. Extract the first row and the last column as seperate tensors.

In [18]:
torch.manual_seed(42)

# Create a 2D tensor of shape (4, 4) with random values
tensor_2d = torch.randn(4, 4)

# Extract the first row as a separate tensor
first_row = tensor_2d[0, :]

# Extract the last column as a separate tensor
last_column = tensor_2d[:, -1]

# Print the first row and last column tensors
print("First Row:")
print(first_row)

print("\nLast Column:")
print(last_column)

First Row:
tensor([ 1.9269,  1.4873,  0.9007, -2.1055])

Last Column:
tensor([-2.1055, -1.6047, -1.4036,  0.7624])


8. Create a 2D tensor of shape (3, 3) and a 1D tensor of shape (3,). Add the 1D tensor to each row of the 2D tensor using broadcasting.

In [141]:
# Create a 2D tensor of shape (3, 3)
tensor_2d = torch.tensor([[1, 2, 3],
                          [4, 5, 6],
                          [7, 8, 9]])

# Create a 1D tensor of shape (3,)
tensor_1d = torch.tensor([10, 20, 30])

# Add the 1D tensor to each row of the 2D tensor using broadcasting
# result = tensor_2d + tensor_1d[:, None]
result = tensor_2d + tensor_1d.unsqueeze(1)
# result = tensor_2d + tensor_1d

# Print the resulting tensor
print(result)

tensor([[11, 12, 13],
        [24, 25, 26],
        [37, 38, 39]])


In [140]:
tensor_edris = torch.arange(10).unsqueeze(1)
tensor_edris

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [146]:
# Create the input tensors
batch_size = 3
matrix_size_row = 2
matrix_size_column = 2

# Input tensor 1 of shape (batch_size, matrix_size, matrix_size)
tensor1 = torch.randn(batch_size, matrix_size_row, matrix_size_column)
print("+"*10)
print(tensor1)
print("+"*10)

# Input tensor 2 of shape (batch_size, matrix_size, matrix_size)
tensor2 = torch.randn(batch_size, matrix_size_row, matrix_size_column)
print("+"*10)
print(tensor2)
print("+"*10)

# Perform batch multiplication using torch.bmm()
result = torch.bmm(tensor1, tensor2)

# Print the result
print(result)

++++++++++
tensor([[[-1.4477, -0.5346],
         [ 0.4590,  1.0935]],

        [[-0.2637, -0.2296],
         [ 2.2003, -0.7842]],

        [[-2.3885,  1.1878],
         [-0.0755,  0.8630]]])
++++++++++
++++++++++
tensor([[[ 1.1685,  1.6792],
         [-0.2999,  0.5672]],

        [[-0.6570,  0.2300],
         [ 0.1725,  1.0249]],

        [[ 0.2223, -0.7381],
         [-0.9258, -1.3517]]])
++++++++++
tensor([[[-1.5312, -2.7343],
         [ 0.2084,  1.3912]],

        [[ 0.1337, -0.2959],
         [-1.5809, -0.2978]],

        [[-1.6307,  0.1575],
         [-0.8158, -1.1108]]])


In [153]:
def bmm(tensor1, tensor2):
    batch_size, n, m1 = tensor1.size()
    _, m2, p = tensor2.size()

    assert m1==m2, "zarb momken nis"

    tenso

    result = torch.zeros(batch_size, n, p)

    for i in range(batch_size):
        result[i] = torch.mm(tensor1[i], tensor2[i])

    return result

In [154]:
bmm(tensor1, tensor2)

tensor([[[-1.5312, -2.7343],
         [ 0.2084,  1.3912]],

        [[ 0.1337, -0.2959],
         [-1.5809, -0.2978]],

        [[-1.6307,  0.1575],
         [-0.8158, -1.1108]]])